CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM(
        'CUSTOMER',
        'RESTAURANT_OWNER',
        'RESTAURANT_MANAGER',
        'RESTAURANT_STAFF',
        'DONATION_ORG',
        'ADMIN',
        'PLATFORM_OWNER'
    ) NOT NULL DEFAULT 'CUSTOMER',
    membership ENUM('FREE', 'PREMIUM') NOT NULL DEFAULT 'FREE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);